version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "mail_service"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - core-service-network
  rabbitmq:
    image: rabbitmq:3.10.7-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - core-service-network
  core-service:
    image: core-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - core-service-network
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: user
      DB_PASSWORD_PASSWORD: password
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_USERNAME: user
      RABBIT_PASSWORD_PASSWORD: password

networks:
  core-service-network:
    external: true