spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD_PASSWORD:password}
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/mail_service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master-postgres.xml
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: 5672
    username: ${RABBIT_USERNAME:user}
    password: ${RABBIT_PASSWORD_PASSWORD:password}

server:
  port: 8081
queue:
  save-and-send: save_and_send_message_queue
  get-unique-message: get_unique_message_queue
  send-to-mail-service: send_to_mail_service_queue
  send-from-mail-service: send_from_mail_service_queue


